export const familyMembers = [
  {
    id: 1,
    family_id: 1,
    date_of_enrollment: '2020-10-09T04:00:00.000Z',
    household_type: 'Adults and Children',
    length_of_stay: '16 weeks',
    demographics: {
      first_name: 'Thomas',
      last_name: 'Shelby',
      gender: 'male',
      relationship: 'Dad',
      DOB: '1-03-1988',
      SSN: 9999,
      income: 20000,
      employer: 'union',
      race: ['White'],
      ethnicity: 'Caucasian',
    },
    barriers: {
      alcohol_abuse: true,
      developmental_disabilities: false,
      chronic_health_issues: false,
      drug_abuse: false,
      HIV_AIDs: false,
      mental_illness: false,
      physical_disabilities: true,
      list_indefinite_conditions: 'NA',
      list_issues: 'NA',
    },
    schools: {
      highest_grade_completed: '12th grade',
      enrolled_status: false,
      reason_not_enrolled: 'finished',
      attendance_status: 'inactive',
      school_type: 'NA',
      school_name: 'NA',
      mckinney_school: false,
    },
    case_members: 3,
    predicted_exit_destination: 'permanent exit',
    flag: null,
    percent_complete: 0,
  },
  {
    id: 2,
    family_id: 1,
    date_of_enrollment: '2020-10-09T04:00:00.000Z',
    household_type: 'Adults and Children',
    length_of_stay: '16 weeks',
    demographics: {
      first_name: 'Jacob',
      last_name: 'Shelby',
      gender: 'female',
      relationship: 'Son',
      DOB: '10-23-2015',
      SSN: 9999,
      income: 20000,
      employer: null,
      race: ['White'],
      ethnicity: 'Caucasian',
    },
    barriers: {
      alcohol_abuse: false,
      developmental_disabilities: false,
      chronic_health_issues: false,
      drug_abuse: false,
      HIV_AIDs: false,
      mental_illness: false,
      physical_disabilities: false,
      list_indefinite_conditions: 'NA',
      list_issues: 'NA',
    },
    schools: {
      highest_grade_completed: 'Pre-Kindergarten',
      enrolled_status: true,
      reason_not_enrolled: 'N/A',
      attendance_status: 'active',
      school_type: 'elementary',
      school_name: 'Wright',
      mckinney_school: false,
    },
    case_members: 3,
    predicted_exit_destination: 'temporary exit',
    flag: null,
    percent_complete: 0,
  },
  {
    id: 3,
    family_id: 1,
    date_of_enrollment: '2020-10-09T04:00:00.000Z',
    household_type: 'Adults and Children',
    length_of_stay: '16 weeks',
    demographics: {
      first_name: 'Maria',
      last_name: 'Shelby',
      gender: 'female',
      relationship: 'Mom',
      DOB: '12-03-1992',
      SSN: 9999,
      income: 20000,
      employer: null,
      race: ['White'],
      ethnicity: 'Caucasian',
    },
    barriers: {
      alcohol_abuse: false,
      developmental_disabilities: false,
      chronic_health_issues: false,
      drug_abuse: false,
      HIV_AIDs: false,
      mental_illness: false,
      physical_disabilities: false,
      list_indefinite_conditions: null,
      list_issues: null,
    },
    schools: {
      highest_grade_completed: '12th grade',
      enrolled_status: false,
      reason_not_enrolled: 'finished',
      attendance_status: 'inactive',
      school_type: null,
      school_name: null,
      mckinney_school: false,
    },
    case_members: 3,
    predicted_exit_destination: 'temporary exit',
    flag: null,
    percent_complete: 0,
  },
];
